language: php
php:
  - 7.2
  - 7.4
before_install:
  - travis_retry composer self-update
  - yes | pecl install imagick
  - composer install
  - composer require paragonie/sodium_compat
script: ./vendor/bin/phpunit
